# Generated by Django 6.0.2 on 2026-02-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição Curta')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('duracao_dias', models.IntegerField(verbose_name='Duração em Dias')),
                ('imagem', models.ImageField(upload_to='expedicoes/', verbose_name='Imagem de Destaque')),
                ('ativa', models.BooleanField(default=True, verbose_name='Reserva Aberta?')),
            ],
        ),
    ]
