# Generated by Django 6.0.3 on 2026-05-08 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedicao',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Expedição', 'verbose_name_plural': 'Expedições'},
        ),
        migrations.AddField(
            model_name='expedicao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expedicao',
            name='descricao_completa',
            field=models.TextField(blank=True, help_text='Descrição detalhada da expedição', verbose_name='Descrição Completa'),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='destino',
            field=models.CharField(blank=True, max_length=200, verbose_name='Destino / Local'),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('moderado', 'Moderado'), ('dificil', 'Difícil'), ('extremo', 'Extremo')], default='moderado', max_length=20, verbose_name='Nível de Dificuldade'),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='expedicoes/', verbose_name='Imagem 2'),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='expedicoes/', verbose_name='Imagem 3'),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço (R$)'),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='vagas',
            field=models.IntegerField(default=20, verbose_name='Vagas Disponíveis'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='data_fim',
            field=models.DateField(verbose_name='Data de Volta'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='descricao',
            field=models.TextField(help_text='Breve descrição da expedição (exibida nos cards)', verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='imagem',
            field=models.ImageField(upload_to='expedicoes/', verbose_name='Imagem Principal'),
        ),
    ]
