# Generated by Django 6.0.3 on 2026-05-08 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expedicao_options_expedicao_atualizado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Data da Reserva')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', max_length=20, verbose_name='Status')),
                ('quantidade_pessoas', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Pessoas')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais ou pedidos especiais', verbose_name='Observações')),
                ('expedicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.expedicao', verbose_name='Expedição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_reserva'],
                'unique_together': {('usuario', 'expedicao')},
            },
        ),
    ]
