# Generated by Django 6.0.3 on 2026-05-11 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reserva'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='expedicao',
            name='duracao_dias',
        ),
        migrations.RemoveField(
            model_name='expedicao',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='expedicao',
            name='imagem_2',
        ),
        migrations.RemoveField(
            model_name='expedicao',
            name='imagem_3',
        ),
        migrations.RemoveField(
            model_name='expedicao',
            name='vagas',
        ),
        migrations.AddField(
            model_name='expedicao',
            name='vagas_totais',
            field=models.IntegerField(default=20, verbose_name='Vagas Totais'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total (R$)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Unitário Pago (R$)'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Atual (R$)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='expedicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.expedicao', verbose_name='Expedição'),
        ),
        migrations.CreateModel(
            name='ImagemExpedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='expedicoes/')),
                ('is_principal', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('expedicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.expedicao')),
            ],
            options={
                'verbose_name': 'Imagem da Expedição',
                'verbose_name_plural': 'Imagens da Expedição',
                'ordering': ['-is_principal', 'ordem'],
            },
        ),
    ]
