# Generated by Django 6.0.3 on 2026-05-12 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reserva_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('confirmada_e_pronta', 'Confirmada e Pronta'), ('lista_espera', 'Lista de Espera'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricoes_alimentares', models.TextField(blank=True, verbose_name='Restrições Alimentares')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=5, verbose_name='Tipo Sanguíneo')),
                ('contato_emergencia', models.CharField(max_length=255, verbose_name='Contato de Emergência (Nome e Telefone)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='core.reserva')),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_id', models.CharField(blank=True, help_text='ID da transação no Mercado Pago/Stripe', max_length=255, null=True, verbose_name='ID no Gateway')),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito')], max_length=50, verbose_name='Método de Pagamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('qr_code_pix', models.TextField(blank=True, null=True, verbose_name='PIX Copia e Cola')),
                ('link_recibo', models.URLField(blank=True, null=True, verbose_name='Link do Recibo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.reserva')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
