# Generated by Django 6.0.3 on 2026-05-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reserva_status_fichamedica_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='nome_completo',
            field=models.CharField(default='Não informado', max_length=150, verbose_name='Nome Completo do Participante'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Reserva Aberta?'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='data_inicio',
            field=models.DateField(db_index=True, verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_medicas', to='core.reserva'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('confirmada_e_pronta', 'Confirmada e Pronta'), ('lista_espera', 'Lista de Espera'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], db_index=True, default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
